import { NextResponse } from 'next/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: Request) {
  try {
    const body = await req.json()
    const { name, businessName, phone, servicesInterested, budgetRange } = body

    // Basic server-side validation
    if (!name || !phone || !servicesInterested) {
      return NextResponse.json(
        { error: 'Name, phone, and services interested are required fields.' },
        { status: 400 }
      )
    }

    const recipient = process.env.AUDIT_RECIPIENT_EMAIL || 'thethreeamigosdm@gmail.com'

    const { data, error } = await resend.emails.send({
      from: 'TTA Audits <onboarding@resend.dev>',
      to: [recipient],
      subject: `New Marketing Audit Request: ${name}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; border-radius: 12px; background-color: #ffffff;">
          <h2 style="color: #7c3aed; margin-top: 0; font-size: 20px; font-weight: bold;">New Free Audit Request</h2>
          <p style="font-size: 14px; color: #4b5563; margin-bottom: 24px; line-height: 1.5;">A new free marketing audit has been requested from the website form submission.</p>
          
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tr style="border-bottom: 1px solid #f3f4f6;">
              <td style="padding: 12px 0; font-weight: bold; color: #1f2937; width: 160px;">Client Name:</td>
              <td style="padding: 12px 0; color: #4b5563;">${name}</td>
            </tr>
            <tr style="border-bottom: 1px solid #f3f4f6;">
              <td style="padding: 12px 0; font-weight: bold; color: #1f2937;">Business Name:</td>
              <td style="padding: 12px 0; color: #4b5563;">${businessName || 'N/A'}</td>
            </tr>
            <tr style="border-bottom: 1px solid #f3f4f6;">
              <td style="padding: 12px 0; font-weight: bold; color: #1f2937;">Phone / WhatsApp:</td>
              <td style="padding: 12px 0; color: #4b5563;">${phone}</td>
            </tr>
            <tr style="border-bottom: 1px solid #f3f4f6;">
              <td style="padding: 12px 0; font-weight: bold; color: #1f2937;">Service Interested:</td>
              <td style="padding: 12px 0; color: #4b5563;">${servicesInterested}</td>
            </tr>
            <tr>
              <td style="padding: 12px 0; font-weight: bold; color: #1f2937;">Budget Range:</td>
              <td style="padding: 12px 0; color: #4b5563;">${budgetRange || 'N/A'}</td>
            </tr>
          </table>

          <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 30px 0;" />
          <p style="font-size: 11px; color: #9ca3af; text-align: center;">This is an automated request generated by The Three Amigos Website Form.</p>
        </div>
      `
    })

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ success: true, data })
  } catch (err: any) {
    return NextResponse.json({ error: err.message || 'Internal Server Error' }, { status: 500 })
  }
}
